Phase4
aureliebcx/mth6412b-starter-code pull request #22
Opened 2019-11-19 00:50 UTC by aureliebcx

Toujours un pb sur HK : la borne inférieure du cout minimal grandit de manière non bornée.

2019-11-21 18:24 UTC, decouvelaere commented on projet/phase4/HK.jl
> +    edges_true_weight = deepcopy(edges_graphe)
edges_true_weight = getEdges(graphe_input)
Cela me paraît plus rapide que de refaire un deepcopy

2019-11-21 18:37 UTC, decouvelaere commented on projet/phase4/HK.jl
> +    edge2, index2 = findmin(edges)
Ne devrait-on pas vérifier ici aussi (comme pour edge1) que edge2 n'est pas une boucle?

2019-11-21 18:38 UTC, decouvelaere commented on projet/phase4/HK.jl
> +end
On pourrait remplacer le "if" par un "while" afin d'éliminer toutes les boucles (arêtes reliées à elles-mêmes) du graphe

2019-11-21 18:44 UTC, decouvelaere reviewed
Améliorations possibles de HK

2019-11-21 18:44 UTC, decouvelaere commented on projet/phase4/HK.jl
> +    lastNode = isequal(getNode1(edge2), racine) ? getNode2(edge2) : getNode1(edge2)
edges_min!() pourrait renvoyer également les deux noeuds auxquels racine est reliée, pour éviter de devoir faire ces tests

2019-11-24 22:46 UTC, mtanneau requested changes

2019-11-24 22:46 UTC, mtanneau commented on projet/phase1/graph.jl
>      weight = 0
`weight` est le nom d'une fonction. Utilisez `w` plutôt.

2019-11-24 22:46 UTC, mtanneau commented on projet/phase1/graph.jl
>          weight = weight + edge.weight
`w += weight(edge)`

2019-11-24 22:46 UTC, mtanneau commented on projet/phase3/main.jl
> +    weight = 0
Utilisez `w` plutôt, pour ne pas avoir de conflit avec la fonction `weight`

2019-11-24 22:46 UTC, mtanneau commented on projet/phase3/main.jl
> +        weight = weight + edge.weight
`w += weight(edge)`

2019-11-24 22:46 UTC, mtanneau commented on projet/phase4/HK.jl
> +    edges_true_weight = deepcopy(edges_graphe)
Ici le `deepcopy` est justifié : sinon on risque de modifier les poids des arêtes du graphe.

2019-11-24 22:46 UTC, mtanneau commented on projet/phase4/HK.jl
> +    sum = 0
`sum` est le nom d'un fonction.
Utilisez `s` par exemple.

2019-11-24 22:46 UTC, mtanneau commented on projet/phase4/HK.jl
> +    edge1, edge2 = edges_min!(edges_racine)
Les deux arêtes reliant la racine au 1-arbre dépendent du poids _avec modification_ : ces deux arêtes doivent être re-calculées à chaque itération !

2019-11-24 22:46 UTC, mtanneau commented on projet/phase4/HK.jl
> +            sum += pi[i] * d[i]
Il faut ré-initialiser `s` à `0` avant le début de la boucle, sinon `s` risque d'augmenter indéfiniment...

2019-11-24 22:46 UTC, mtanneau commented on projet/phase4/HK.jl
> +        k += 1
Vous pouvez rajouter un log à chaque itération (ou bien toutes les `q` itérations, où `q` est un paramètre).
Par exemple :
```
#Iter       C*          W
    0     1000       0.00
   10      983      57.23
   20      592     124.98
```

2019-11-24 22:46 UTC, mtanneau commented on projet/phase4/HK.jl
> +function gradient(graphe::Graph{T}, node::AbstractNode{T}) where T
Vous pouvez calculer le degré de tous les nœuds en un seul passage sur les arêtes.

2019-11-24 22:46 UTC, mtanneau commented on projet/phase4/HK.jl
> +function getRealWeight(arbre::Graph{T}, edges::Vector{Edge{T}}) where T
cf correction rapport.

Vous pouvez calculer la borne inférieure `W` directement, sans calculer le poids (non-modifié) du 1-arbre.

2019-11-24 22:46 UTC, mtanneau commented on projet/phase4/RSL.jl
> +#= Mauvaise fonction
Vous pouvez supprimer cette partie du code si elle n'est pas utilisée.

2019-11-27 15:16 UTC, closed without merging